### ISSUE TITLE
Running model on CPU

### ISSUE THREAD

**Issue by abi98213** [huuuuusy/Mask-RCNN-Shiny#6]
Hello @huuuuusy  thanks for this great implementation.
I want to run this code on my laptop which does not have GPU, when I set 
```

GPU_COUNT = 0
IMAGES_PER_GPU = 0
```
It gives the following error 
` str(inputs) + '. All inputs to the layer '
ValueError: Layer roi_align_classifier was called with an input that isn't a symbolic tensor. Received type: <class 'list'>. Full input: [[], <tf.Tensor 'input_image_meta:0' shape=(?, 93) dtype=float32>, <tf.Tensor 'fpn_p2/BiasAdd:0' shape=(?, ?, ?, 256) dtype=float32>, <tf.Tensor 'fpn_p3/BiasAdd:0' shape=(?, ?, ?, 256) dtype=float32>, <tf.Tensor 'fpn_p4/BiasAdd:0' shape=(?, ?, ?, 256) dtype=float32>, <tf.Tensor 'fpn_p5/BiasAdd:0' shape=(?, ?, ?, 256) dtype=float32>]. All inputs to the layer should be tensors.
`

Please tell me how I can run this on cpu. And is there any way I can fast this code for inference.

**Comment by Rajasekhar06** [comment]
@mabdullahrafique How did you solved that issue!
